FROM python:3.13.9-slim

WORKDIR /app

RUN adduser --disabled-password --gecos '' appuser && chown -R appuser:appuser /app
USER appuser

COPY pyproject.toml ./
RUN ["pip", "install", "-e", "."]

COPY src/publisher/ ./src/publisher
COPY tests/ ./tests/

ENV PYTHONPATH="src"
ENV AGG_HOST="0.0.0.0"
ENV AGG_PORT=7878

CMD ["python", "-u", "./src/publisher/stress_test.py"]
